### ISSUE TITLE
[bug] - Multiple @connections generate invalid codeGen (Missing line breaks)

### ISSUE THREAD

**Issue by dan003400** [zth/rescript-relay#168]
The following query will result in compiler errors only in **Mutation** responses:

```user {
  posts(first: 1000) @connection(key: "UserPage_query_posts") {
    edges {
       node {
          id
        }
    }
  }
  comments(first: 1000) @connection(key: "UserPage_query_comments") {
    edges {
       node {
          id
        }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/1211542/112394302-7c340b00-8cca-11eb-9c7f-370ddd8fc6ab.png)

**Comment by zth** [comment]
This should be fixed in `rescript-relay@0.16.0+` I think. Please try upgrading to that if you haven't already and re-open this if it still doesn't work.
