### ISSUE TITLE
[RFC] PPX-less/pure mode

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#174]
There's interest in having a "pure" mode for RescriptReact (cc @webican), which avoids the use of PPX, and avoids automatic runtime conversion. This issue serves as a place to discuss how we could make that happen. It'd be purely additive, meaning you could opt in to it. 

Important to note is that the "preferred"/"official" way would still be to use the PPX, since one of the important corner stones in why RescriptRelay was created at all is to improve the DX of using Relay by leveraging things like a PPX to plumb together the generated code by the Relay compiler, etc. But different users will have different needs, and I think we have most things in place already to cater to this need too. Let's make everyone happy! 😄 

## Goals
Here are some of the goals a "pure" mode should have, in my opinion. Please feel free to discuss this so we can reach something together.
- No PPX. Let's aim for getting rid of the PPX altogether in this mode.
- No runtime conversion. Don't autoconvert things like nullables, fragment refs and unions, and let the user do that "by hand" themselves when needed.
- Aim for the generated code to be as close to writing stock Relay JS code as possible.

## Steps to get there
I'll detail this more shortly, but at a first glance, I think we'll need the following:

### A way of writing GraphQL tags without leveraging the PPX extension node syntax
This can probably be something simple, like ```let _ = RescriptRelay.graphql(`fragment SomeFragment ...`)```. Worth noting here is that _we won't use the definition_ in the code. The Relay compiler just needs _something_ it can recognize and pick the GraphQL code up from. So, ideally, whatever we define there should be voided and not included in the generated code (as that's not needed). So, it could be anything really, as it won't be used at runtime.

This should be separate from the current, regular definition (`%relay(`), and preferable be what distinguishes that the fragment is in "light mode" or not.

### A compiler mode for ouputing raw values
Needs to do the following:
- Output nullables as `Js.Nullable.t`
- Output unions unconverted + document how to manually convert them at runtime (`someObj.someUnion->path_to_SomeUnion_wrap`)
- Output an identity function to convert any record that has fragment refs into its fragment refs type. `external name_of_record_getFragmentRefs: name_of_record => RescriptRelay.fragmentRefs<[ | #FragmentRefHere_user ]> = "%identity"`

Worth noting that all of this has been how RescriptRelay has worked at _some point_ of its life 😄  So putting this together shouldn't be that hard.

### Bindings that can unwrap the generated modules
One idea is trying to land in an API similar to this:
```
// Avatar.res
let _ = RescriptRelayPure.graphql(`
  fragment Avatar_user on User {
    firstName
    lastName
  }
`)

@react.component
let make = (~user) => {
  let fragmentData = RescriptRelayPure.useFragment(module(Avatar_user_graphql), user)
}
```

```
// UserHeader.res
let _ = RescriptRelayPure.graphql(`
  fragment UserHeader_user on User {
    friendCount
    ...Avatar_user
  }
`)

@react.component
let make = (~user) => {
  let fragmentData = RescriptRelayPure.useFragment(module(UserHeader_user_graphql), user)

  // getFragmentRefs_fragment is an external identity function that turns the fragment record into `RescriptRelay.fragmentRefs<[ | #Avatar_user ]>`
  <Avatar user={UserHeader_user_graphql.getFragmentRefs_fragment(fragmentData)} />
}
```

_This will be expanded in time_

**Comment by webican** [comment]
This is awesome! Thank you @zth!

Now, a couple of observations:

## Goals
With the release of 9.0 Rescript is now openly following a "zero-cost" philosophy [https://rescript-lang.org/blog/release-9-0](https://rescript-lang.org/blog/release-9-0) and [https://github.com/bobzhang/zero-cost-rescript](https://github.com/bobzhang/zero-cost-rescript) which seems to sum up the goal of what we are trying to achieve here pretty as well. I'd call this mode `RescriptRelayZero` - what do you think?

## Types
Oh, I like the idea of passing in a whole generated graphql module to useFragment function, it should make it possible to use the generated types within that module to return a fixed fragment type using RescriptRelay functions.

Right now I have to bring in the fragment type manually into scope when using my custom bindings:
```
let fragmentData: UserHeader_user_graphql.Types.fragment = useFragment(UserHeader_user_graphql.node, user)
```

## PPX
I wouldn't mind using PPX for things that don't affect the Js output. For example generating a module alias so that the following:
```
module User = %relayzero(`
  fragment UserHeader_user on User {
    friendCount
    ...Avatar_user
  }
`)
```
becomes:
```
module User = UserHeader_user_graphql
```
and so one can use it like this:
```
// UserHeader.res
module User = %relayzero(`
  fragment UserHeader_user on User {
    friendCount
    ...Avatar_user
  }
`)

@react.component
let make = (~user) => {
  let fragmentData = RescriptRelayPure.useFragment(module(User), user)

  <Avatar user={User.getFragmentRefs_fragment(fragmentData)} />
}
```
But if you decide it would be best to get rid of PPX entirely, I would be fine with that too.

**Comment by zth** [comment]
Quick answer, but my initial hunch is that the mode should get rid of the PPX all together. The downside is obviously that you'll need to understand that a separate module is generated by the compiler. That might be annoying at first, but it is an integral part of how RescriptRelay works (and you'll be exposed to that anyway), so I think the benefits might outweigh the costs. It also helps to reduce any chance of dependency cycles etc.

**Comment by zth** [comment]
Closing this. Can re-open when there's time/more interest in something like this, but as of now this is unlikely to be prioritized anytime soon.
