### ISSUE TITLE
Publish canary versions to npm

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#178]
It'd be really cool to publish canary versions for each main commit to npm. Prior art here: https://github.com/Astrocoders/lenses-ppx/blob/master/.github/workflows/pipeline.yml

It's a bit less convenient in RescriptRelay as we build two separate binaries for each arch we support, but still doable.

**Comment by zth** [comment]
I think I finally got this working.

**Comment by mellson** [comment]
Thanks, this really helped me out today!
