### ISSUE TITLE
How should null be mapped?

### ISSUE THREAD

**Issue by mellson** [zth/rescript-relay#186]
Since null is a part of graphql it would be good with a nice way to express this in the ReScript code. This ticket is a place for discussing ideas on how to solve it

**Comment by zth** [comment]
Just adding some context - what we're primarily talking about is _null as input_. Null in itself is currently automatically converted to `undefined` by RescriptRelay, so it can map cleanly to ReScript's `option` type. But, this conversion is problematic in the odd cases where you need to actually send `null` to the server as an input.

**Comment by zth** [comment]
Closing this as IIRC it turns out the spec says that null and not providing the variable at all should be interchangeable.
