### ISSUE TITLE
Multiple fragmentRefs in generated mutation code

### ISSUE THREAD

**Issue by believer** [zth/rescript-relay#187]
I've got a mutation that looks something like:

```graphql
mutation AddMovieMutation(...) {
	insert_movie_one(...) {
		id
		year
		title
		...Genres_movie
		...Poster_movie
		...Ratings_movie
	}
}
```

However, each fragment generates a `fragmentRefs` argument:

```rescript
let make_response_insert_movie_one = (
	~id,
	~year=?,
	~title,
	~fragmentRefs,
	~fragmentRefs,
	~fragmentRefs,
	()
): response_insert_movie_one => {
	id: id,
	year: year,
	title: title,
	fragmentRefs: fragmentRefs,
	fragmentRefs: fragmentRefs,
	fragmentRefs: fragmentRefs
}
```

Is it not possible to use fragments in the mutation response or am I doing something wrong? 😄

**Comment by zth** [comment]
@believer oh, great catch! 😄 That just looks like an oversight, your approach should be totally fine and is valid. Those generated make functions are a bit hairy in these circumstances, but it should definitively be possible to do what you're doing. Likely a pretty easy fix, let me look in to it as soon as I can.

**Comment by zth** [comment]
@believer As a temporary workaround, if you're just after including the fragment data in what gets resolved from the server (and not actually access that data as a fragment from the mutation response), you can add `@raw_response_type` to the mutation. That'll make Relay flatten the types generated, removing the fragment refs (and by that this particular issue).

**Comment by believer** [comment]
Great suggestion and nice that I'm doing everything correctly! I tried adding `@raw_response_type`, but I'm still seeing the same error 🤔 I haven't used it before, but I would use it like below from what I can tell? The Relay compiler seems happy with it as well.

```graphql
mutation AddMoviePageMutation(...) @raw_response_type {
	insert_movie_one(...) {
		id
		...
	}
}
```

**Comment by zth** [comment]
@believer hm, ok, that's a bit weird! What's the error exactly?

**Comment by believer** [comment]
Yeah, I don't know 😅 Here's the error from the ReScript compiler:

```>>>> Start compiling
bsb: [3/4] src/__generated__/AddMoviePageMutation_graphql-Web.cmj
FAILED: src/__generated__/AddMoviePageMutation_graphql-Web.cmj

  We've found a bug for you!
  /code/personal/movies/packages/web/src/__generated__/AddMoviePageMutation_graphql.res:1232:35-1239:3

  1230 ┆   ~fragmentRefs,
  1231 ┆   ()
  1232 ┆ ): response_insert_movie_one => {
  1233 ┆   id: id,
     . ┆ ...
  1238 ┆   fragmentRefs: fragmentRefs
  1239 ┆ }
  1240 ┆ let makeOptimisticResponse = (
  1241 ┆   ~insert_movie_one=?,

  The record field label fragmentRefs is defined several times

FAILED: cannot make progress due to previous errors.
>>>> Finish compiling(exit: 1)
``

**Comment by zth** [comment]
@believer that particular error should be fixed here: https://github.com/zth/rescript-relay/commit/a12afdb3f29133c9d7224a4c254eb81aec537427

Let me put out a release tonight and we'll see if it does the trick. I'll keep this open until we've verified. Thanks for finding this 😄 👍

**Comment by believer** [comment]
Oooh, that's awesome! I'll try it immediately once it's been released.

No, thank you for the great and super fast help! 😄

**Comment by zth** [comment]
@believer released in `0.19.0` - let me know how it works!

**Comment by believer** [comment]
@zth it worked like a charm! Thanks again! 😄

**Comment by zth** [comment]
Excellent!
