### ISSUE TITLE
[RFC] useLazy for fragments

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#201]
Inspired by [this issue](https://github.com/facebook/relay/issues/3486) talking about a potential lazy version of `useFragment`, we could implement the solution that Joe Savona is describing today in RescriptRelay. It could look something like this:

```
module UserFragment = %relay(`
  fragment SomeFragment_user on User @refetchable("SomeFragmentRefetchQuery") {
     some
     props
     here
  }
`)

// Use it like normal
UserFragment.use(someFragmentRefs)

// Or, use it lazily
let { node: user } = UserFragment.useLazy(~variables={id: someProp.userId}, ());

switch user {
  | Some(user) => ...
```

This would be transformed to a `useLazyLoadQuery` targeting the refetch query generated for `SomeFragment_user`, but doing the plumbing/wiring automatically/under the hood.

We could even take it a step further and shortcut the node interface for the user too to make it a bit more ergonomic, so that the API could be:

```
let user = UserFragment.useLazy(~variables={id: someProp.userId}, ());

switch user {
  | Some(user) => ...
}
```

An, in my opinion, pretty interesting approach and quite an ergonomic solution to the classical "more details" example.

Does anyone have thoughts on this?

**Comment by zth** [comment]
Basic implementation here (with the most relevant parts highlighted): https://github.com/zth/rescript-relay/pull/202/files#diff-3b92c8c1ba478cf1946f6fd14b06517bbc48181f615ac6503860aec813511183R1-R20

**Comment by mellson** [comment]
This is awesome 👏 Great work @zth

**Comment by zth** [comment]
Thank you @mellson !

**Comment by zth** [comment]
I think this is a nice addition, but I want to hide it behind an experimental flag before I merge this. Figuring out the best way to do that now.

**Comment by zth** [comment]
This was a cool experiment, but I'm closing this for now. If there's interest for something like this, please feel free to ping me and we can reconsider.
