### ISSUE TITLE
The code generated by ppx violates the rules of hooks.

### ISSUE THREAD

**Issue by jeong-sik** [zth/rescript-relay#205]
When to use eslint rules-of-hooks

`React Hook "Hooks.useLazyLoadQuery" is called in function "use$1" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter`

I know it's not an important issue. However, it would be nice to have a setting that puts a prefix in the function that starts with `use`.

**Comment by zth** [comment]
I think this is the eslint rule not accounting for the $ sign in the variable name, right? Anyway, thanks for posting this, but unfortunately this is out of RescriptRelay's control. The PPX does in fact generate function names that are valid, but what you see is what the ReScript compiler ends up compiling the name to. And we unfortunately have little control over that.

I'd recommend turning off eslint for the generated files completely to be honest.

**Comment by zth** [comment]
I'll go ahead and close this one since it's from my understanding out of our control.
