### ISSUE TITLE
Remove dependency on reason-promise

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#209]
This was a bad idea to depend on from the beginning (my mistake!), and since it's only used in very few places, we should go ahead and just remove it. It's a breaking change though sadly, but it's for the greater good.

**Comment by zth** [comment]
Will wait for [this](https://forum.rescript-lang.org/t/rfc-new-promise-binding/963/42) to land before proceeding here.

**Comment by cometkim** [comment]
I tried to use [ReScript-JS](https://github.com/bloodyowl/rescript-js), which is depending on [ReScirpt Promise](https://github.com/ryyppy/rescript-promise)

And ReScript Promise and Reason Promise both are use `Promise` module without namespace :sweat_smile:

**Comment by zth** [comment]
Update: Since the core team haven't shipped the new bindings yet, we'll revert from `rescript-promise` back to `Js.Promise` so people can use the new bindings if they want.
