### ISSUE TITLE
fetchKey ignored when preloading queries

### ISSUE THREAD

**Issue by mellson** [zth/rescript-relay#220]
When trying to preload data using the [description here](https://rescript-relay-documentation.vercel.app/docs/experimental-router#preloading-data-with-the-router) I'm having some problems setting a fetchKey, it seems to be ignored:

```
Dashboard(
        DashboardQuery_graphql.load(
          ~environment=RelayEnv.environment,
          ~variables=(),
          ~fetchPolicy=StoreOrNetwork,
          ~fetchKey="ignoredKey"
          (),
        ),
      )
```

When I look at the query printed to the console the fetchKey is ignoring my value, and also for me it's always a number but the type in load is string. So not sure which type is correct, maybe it's just chance that all my fetchKeys are numbers.

**Comment by zth** [comment]
After looking into this, the bindings actually seem right from my perspective. This is what the generated code looks like:
```
var load = function (environment, variables, fetchPolicy, fetchKey, networkCacheConfig, param) {
    return Hooks.loadQuery(environment, C.query, Curry._1(C.convertVariables, variables), {
                fetchKey: fetchKey,
                fetchPolicy: mapFetchPolicy(fetchPolicy),
                networkCacheConfig: networkCacheConfig
              });
  };
```

Could you check again and re-open if it really doesn't work?
