### ISSUE TITLE
The router reloads on client side navigation without url changes

### ISSUE THREAD

**Issue by mellson** [zth/rescript-relay#221]
To me, it seems like `RescriptRelayRouter` can cause rerenders of the route when the url is updated, even though the route data doesn't change.

Example:
I have a url `/locations/stockholm` which has matched to these routeParams: `Some(City(string))`
This is being rendered to a city component:
```
~render=route => 
    {switch route {
    | City(name) => <City name />
    | _ => 
    }}
```

If I now do a client side transition to `/locations/stockholm?venue=debaser` then it'll match to the same routeParams and same route render causing the component to rerender even though nothings really changed.

I can stop the rerendering from happing by using a memoized version of the city component, something like `let make = React.memo(cityComponent)`.
This will stop the rerender since React sees that the only prop, name, is unchanged.

However, when we prepare data for relay using the prepare method, we usually build a new queryRef on every route change. And since a route change can be triggered without modifications to the routeParams this can cause problems.

Because now the queryRef prop will be new each time even though the intent was not to change routes or cause a rerender.

Could this be related to [this issue](https://github.com/facebook/react/issues/17786)? (I don't think so on first glance, but leaving the reference here for now...)

I hope this explanation makes sense, fire any questions you may have...

**Comment by zth** [comment]
This is now changed to only re-rendering on path changes: https://github.com/zth/rescript-relay/commit/4ea7c1db999ec0bddd0896dbaf476b02384c9b64
