### ISSUE TITLE
with relay-compiler v12 generated files include a require statement with a wrong path

### ISSUE THREAD

**Issue by farukg** [zth/rescript-relay#254]
i tried v12 of relay and had an error while bundling.
I think the original relay-compiler just outputs a slightly new format in which it requires a file. Since rescript-relay appends `_graphql` to the generated files it is currently an error:
![image](https://user-images.githubusercontent.com/1577842/133870145-d9a4ef2f-a430-4daa-bc2c-618c27066be8.png)
`correct import path would be OverviewFragment_graphql.bs.js`

I thought it only happens when using bsb and when having @refetchable in a fragment, i tried to reproduce in the example project, but at that time i didnt have the clue that the new version could cause this. After downgrading to 11 the problem vanished.
Reporting already cause this project is usually living on the very edge  :rocket:

**Comment by zth** [comment]
Hey @farukg , thank you for the report!

RescriptRelay isn't yet upgraded to support Relay `12.0.0`, which is probably why it's failing. I'll have a deeper look at this once I get to upgrading the Relay version. Should be in a few weeks or so.
