### ISSUE TITLE
Discord invite link

### ISSUE THREAD

**Issue by mellson** [zth/rescript-relay#267]
Hi @zth the Discord invite link on the docs page is an invite to the docusaurus server. I don't think I can create an invite link that lasts longer than 7 days? That's why I'm creating this as an issue over a PR 😊

**Comment by zth** [comment]
Hmmm, are you sure? For me it leads to the correct server, but I'm already on that server too so maybe that helps.

**Comment by mellson** [comment]
Not 100% sure as I haven't built a docusaurus site myself but shouldn't the discord link in [the config file](https://github.com/zth/rescript-relay/blob/master/rescript-relay-documentation/docusaurus.config.js) point to the RescriptRelay discord in stead of the docusaurus one?

**Comment by zth** [comment]
Oh sorry, you mean _that_ link! 😄  Of course, great catch! I'll fix that.
