### ISSUE TITLE
enum input has wrong type

### ISSUE THREAD

**Issue by mellson** [zth/rescript-relay#281]
Playing with the [new awesome enum features](https://rescript-relay-documentation.vercel.app/docs/enums#dealing-with-the-unsafety-of-enums-from-the-server) I discovered that my input enums was getting the wrong type in the generated code:

![image](https://user-images.githubusercontent.com/167574/148843875-88d2dff0-7808-40d0-af05-ce652f6f37f2.png)

**Comment by zth** [comment]
I accidentally broke this when fixing the other enum things. Will fix soon and publish a new beta!

**Comment by zth** [comment]
Closed in https://github.com/zth/rescript-relay/commit/3326ce213fe46677e6a4b681f58881255e9758ad that's out in 15mins or so.
