### ISSUE TITLE
Provide the compiler output as diagnostics in VSCode

### ISSUE THREAD

**Issue by mellson** [zth/rescript-relay#293]
Currently when you run into relay compilation errors you can't see why in VSCode. You can however run the `rescript-relay-compiler` manually in your project and get the compilers take on what's wrong.

It would be helpful to provide this output in VSCode when running the compiler using the `rescript-relay` extension.

What needs to be done:

- [ ] Parse the new compiler output
- [ ] Produce VSCode diagnostics manually from the parsed output

**Comment by zth** [comment]
Closing in favor of https://github.com/zth/vscode-rescript-relay/issues/36 since the official Relay LSP is now more reasonable to work with and will be possible to use fairly easily.
