### ISSUE TITLE
[feature] Support Relay Resolvers

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#306]
New experimental Relay feature for adding client side derived fields that can be resolved via actual functions. Figure out how to support it.

**Comment by zth** [comment]
Documentation is here: https://relay.dev/docs/next/guides/relay-resolvers/

In short, you extend your schema client side with a new field, that you annotate with `@relayResolver(some config here)`. You then define a resolver that, via a fragment on a specific GraphQL type, takes fragment data and returns derived data. You can then select that field in your other fragments like any other field, and Relay will use your resolver to resolve the data.

Proposed API in ReScript (not finalized, but something along these lines).

```graphql
# someClientExtension.graphql
extend type User {
  fullName: String
    @relay_resolver(
      fragment_name: "UserFullNameResolverFragment"
      import_path: "UserFullNameResolver"
    )
}
```

```rescript
// UserFullNameResolver.res

// This selects all the data from our type that we need to resolve our derived data.
module Fragment = %relay(`
  fragment UserFullNameResolverFragment on User {
    firstName
    lastName
  }
`)

/**
 * @RelayResolver
 *
 * @onType User
 * @fieldName fullName
 * @rootFragment UserFullNameResolverFragment
 *
 * The full name of a user, if available.
 */
type resolverValue = option<string>

include %relay.resolver(user => {
  // `user` is the fragment data from above
  switch user {
    | {firstName: Some(firstName), lastName: Some(lastName)} => Some(`${firstName} ${lastName}`)
    | _ => None
  }
})
```

Using it would then look like this:

```rescript
module UserFragment = %relay(`
  fragment SomeFragment_user on User {
    fullName
  }
`)

@react.component
let make = (~user) => {
  let user = UserFragment.use(user)
  
  // option<string>, resolved via the resolver at runtime
  user.fullName
}
```

**Comment by zth** [comment]
Alternate API:

```rescript
// UserFullNameResolver.res

// Must be defined before the fragment so the PPX can add a function that uses it.
type resolverValue = option<string>

// This selects all the data from our type that we need to resolve our derived data.
module Fragment = %relay(`
  fragment UserFullNameResolverFragment on User {
    firstName
    lastName
  }
`)

/**
 * @RelayResolver
 *
 * @onType User
 * @fieldName fullName
 * @rootFragment UserFullNameResolverFragment
 *
 * The full name of a user, if available.
 */
let default = Fragment.makeRelayResolver(user => {
  // `user` is the fragment data from above
  switch user {
    | {firstName: Some(firstName), lastName: Some(lastName)} => Some(`${firstName} ${lastName}`)
    | _ => None
  }
})
```

This would involve us encoding in  `rescript-relay` that any fragment with a name ending with `ResolverFragment` is a Relay resolver dedicated fragment. And with that, we can adjust the PPX to add `makeRelayResolver` instead of the regular fragment helpers.

I think I prefer this one over the first one.

**Comment by hariroshan** [comment]
Does the version `1.0.0-beta.3` not support client-side schema?
```graphql
extend type SingleThread {
  isTyping: Boolean!
}
extend type Message {
  isRead: Boolean!
}
```
I used `RescriptRelay.RecordProxy.setValueBool(~name="isRead", ~value=true, ())` to update value.
After updating to the above mentioned version it shows following error...
```
[ERROR] ✖︎ The type `SingleThread` has no field `isTyping`. Did you mean `isOnline`?

  src/pages/messaging/messaging/messages/show_messages/LoadThread/LoadThreadFragment.res:16:7
   15 │       isOnline
   16 │       isTyping
      │       ^^^^^^^^
   17 │       avatar {
```
is there a way around it?

**Comment by zth** [comment]
@hariroshan I think the config option changed to `schemaExtensions` for setting explicitly where schema extensions are located. Have a [look at this](https://github.com/facebook/relay/tree/main/packages/relay-compiler#configuration).

**Comment by hariroshan** [comment]
@zth Thank you for the quick reply. Adding `schemaExtensions` to point to the `src` directory fixed the issue. 😄

**Comment by zth** [comment]
I have this working in https://github.com/zth/rescript-relay/compare/relay-resolvers. Needs docs etc.

**Comment by zth** [comment]
Closed by https://github.com/zth/rescript-relay/commit/9ae0703ee185776c921d19799c36907320013a0b
