### ISSUE TITLE
Build error on Vercel machine due to lower GLIBC version available

### ISSUE THREAD

**Issue by vknez** [zth/rescript-relay#308]
Hi!

I encountered an error when running the latest beta of `rescript-relay` on Vercel. It has GLIBC version 2.26, but `rescript-relay-compiler` needs 2.28 or 2.29. It seems connected to #152.

Is there an easy way to compile it in a way so that it doesn’t need the exact GLIBC version?

Vercel build machines use the “Amazon Linux 2 image”, and I believe it wouldn’t be safe to try to upgrade GLIBC to the version required by this package.
https://repost.aws/questions/QUrXOioL46RcCnFGyELJWKLw/glibc-2-27-on-amazon-linux-2

```
$ rescript-relay-compiler
--
/vercel/path0/node_modules/rescript-relay/rescript-relay-compiler.exe: 
/lib64/libc.so.6: version `GLIBC_2.29' not found 
(required by /vercel/path0/node_modules/rescript-relay/rescript-relay-compiler.exe)

/vercel/path0/node_modules/rescript-relay/rescript-relay-compiler.exe: 
/lib64/libc.so.6: version `GLIBC_2.28' not found 
(required by /vercel/path0/node_modules/rescript-relay/rescript-relay-compiler.exe)
```

Thanks!

**Comment by zth** [comment]
Hi! Hmm, I think we'll need to port [this PR](https://github.com/facebook/relay/pull/3754) to the [Relay compiler fork](https://github.com/zth/relay/tree/rescript-relay). Luckily it doesn't look too hard. 

Is this something you'd be willing to take a stab at? It'd basically be about applying the equivalent of that PR to our CI, and then handle detection of when that binary needs to be included.

**Comment by vknez** [comment]
@zth I could try, but I'm not very skilled in that area. How would I test it?

**Comment by zth** [comment]
Yeah thinking a bit more about it, maybe testing it for anyone but me is a bit cumbersome right now...

I don't think it should take too much time to get this going and test this, but I'm swamped at the moment. Will be at least a while before I have a chance to have a look at this unfortunately. Hang in there and I'll have a look as soon as I can!

**Comment by vknez** [comment]
Thanks a lot @zth! 

PS. `rescript-relay` is such a pleasure to use.

**Comment by zth** [comment]
@vknez thank you very much, that makes me very happy you say that! 😄

**Comment by zth** [comment]
@vknez can you give `rescript-relay@0.0.0-linux-musl-d5435e23` a quick try? I tried porting it really quickly.

**Comment by vknez** [comment]
Man, it works!!! 🎉 

Thanks a million!

**Comment by zth** [comment]
@vknez Yay, that's great! This will be in the next beta release.
