### ISSUE TITLE
Querying the `node` field for a single type of node is not type-safe

### ISSUE THREAD

**Issue by jovanbaj** [zth/rescript-relay#324]
Hello,
While using node resolver to fetch data, we have stumbled upon some strange behavior when fetching only one type.
Let’s say that we have a schema like this:

```gql

type Person implements Node {
   id: ID!
   name: String!
}

type House implements Node {
   id: ID!
   address: String!
}

```

When we want to display a page for a `Person`, we can use the node interface to get a specific `Person`.

```res
// PersonPage.res

module Query = %relay(`
  query PersonPageQuery($id: ID!) {
     node(id: $id) {
        ... on Person {
            id
            name
          }
      }
    }
`)

...

let result = Query.use(~variables=Query.makeVariables(~id=personId), ())

 switch result.node {
  | None => Js.log("Nothing to show")
  | Some(person) => Js.log2("Person is now available", person.name->Js.String.toUpperCase)
}

```

If we pass an id of a `House`, we will receive a node, but the app will crash when trying to use `person.name`. Pattern matching only checks if we got the node, not if we got the right type.

Could the solution be to further check if we got the right type of the node with the requested id when pattern matching the node?

You explained how you deal with node resolver when trying to get a single type from it [here](https://github.com/zth/rescript-relay/issues/311#issuecomment-1070518504)

**Comment by zth** [comment]
Good catch! This is a regression actually. Two things need to happen:
- We need to actually do the runtime `__typename` check. This is easy enough.
- We need to ensure that the top level node field optimization is only applied when the single selection is a concrete type, since the runtime check will break on interfaces.

It'll take me a little while to get this sorted because I need to change things in the compiler, but meanwhile you can opt out of the node field optimization by selecting some other type in addition to `Person`. So:
```graphql
 node(id: $id) {
    ... on Person {
        id
       name
    }
    ... on SomeOtherThing {
      id
    }
}
```

Not ideal, but it'll let you move on for now until this is properly fixed.

**Comment by jovanbaj** [comment]
Thank you for looking into it. We will go with that approach for now.

**Comment by zth** [comment]
What version are you on btw?

**Comment by jovanbaj** [comment]
We were on `1.0.0-beta.12 `when we noticed. We upgraded to `1.0.0-beta.18` and the issue was still there.

**Comment by zth** [comment]
Great! I'm having trouble reproducing this, would you be up for opening a PR with a failing test? It should be fairly simple, I'll give you detailed instructions.

**Comment by jovanbaj** [comment]
Of course.

**Comment by zth** [comment]
Actually, before that - would you mind posting a bit more information on how to reproduce? In sum, I'd like the full definition of the query causing the issue, the relevant type definitions from the schema, and the full response from the server (so from the network).

**Comment by jovanbaj** [comment]
I am not able to provide you with my schema, but I was able to make a reproducible demo using your example app. The problem actually occurs when you have a combination of fragment refs and fields from a particular type.

```res
// FailingNode.res

module Fragment = %relay(`
  fragment FailingNode_ticket on Ticket {
    id
    trackingId
  }
`)

module Query = %relay(`
  query FailingNodeQuery($id: ID!) {
     node(id: $id) {
         __typename
         ... on Ticket {
            subject
            ...FailingNode_ticket
          }
      }
    }
`)

@react.component
let make = (~id="SITE_STATISTICS_ID") => {

 let result = Query.use(~variables=Query.makeVariables(~id=id), ())

 switch result.node {
  | None => Js.log("Nothing to show")
  | Some(ticket) => Js.log2("Ticket is now available", ticket.subject->Js.String.toUpperCase)
}

<></>

}
```

**Comment by zth** [comment]
Thank you, that's great! I'm hoping I'll find time to look at this fairly soon.

**Comment by zth** [comment]
@jovanbaj I'm unable to reproduce this in the example. You're essentially just rendering that component, and it blows up because of `ticket.subject`?

**Comment by jovanbaj** [comment]
Yeah, but you need to put a valid node id instead of the `SITE_STATISTICS_ID`. I used an id of the `SiteStatistics` since it also implements node.

**Comment by zth** [comment]
@jovanbaj Will be fixed in `beta.19`, which will be out in 20mins or so. Please give it a spin and let me know if it works.

**Comment by jovanbaj** [comment]
That did the trick! 🎉
Thank you!!!

**Comment by zth** [comment]
@jovanbaj awesome! Thank you for reporting and providing a reproduction!
