### ISSUE TITLE
[Docs] Fragment argument application is not explained

### ISSUE THREAD

**Issue by Kingdutch** [zth/rescript-relay#325]
Inspiration from https://graphql-ppx.com/docs/fragment#variables-within-fragments

https://rescript-relay-documentation.vercel.app/docs/refetching-and-loading-more-data#making-a-fragment-refetchable explains `@argumentDefinitions` but how to actually apply arguments is not explained in the docs.

**Comment by zth** [comment]
This is covered by the regular Relay docs.
