### ISSUE TITLE
[Feature] Support turning off safe enums

### ISSUE THREAD

**Issue by Emilios1995** [zth/rescript-relay#342]
When working with local schema extensions, it's often unnecessary to enforce safety measures (encoding/decoding) around enums. 

The reason is that unless the objects are serialized and stored in some kind of local storage for later retrieval, the values should always be up to date and in sync with the local schema definition.

@zth proposed two features:
- A directive for turning off the safety measures `(enumField @rescriptRelayEnum(unsafe: true) or similar)`
- Honoring the Relay config of “no future proof enums”, which would turn off the safety for all enums in the entire application.

**Comment by zth** [comment]
Fixed in https://github.com/zth/rescript-relay/commit/27017e80775e078345299eeeff6cda0fd4644d31
