### ISSUE TITLE
`format-all-graphql` CLI command doesn't ignore commented code

### ISSUE THREAD

**Issue by reck753** [zth/rescript-relay#343]
Hi! 👋 

`rescript-relay-cli` is an awesome tool which helps a LOT!

However, we stumbled upon a strange behaviour with `format-all-graphql` command. I am not sure if this would apply to `format-single-graphql` as well. More details below.

### Query

For example, let's have this piece of code:
```rescript
// module Query = %relay(`
//   query BookQuery(
//     $bookId: ID!
//   ) {
//     node(id: $bookId) {
//       ... on Book {
//         title
//       }
//     }
//   }
// `)
```

If we didn't compile this code before (and, with it, we didn't generate `BookQuery_graphql.res`), the command would work as expected, ignoring this code and formatting everything else. However, if we compiled and generated the file, and then commented out the code, `format-all-graphql` would report this:
```bash
...

SyntaxError: Syntax Error: Cannot parse the unexpected character "/". (2:1)
  1 |
> 2 | //   query BookQuery($bookId: ID!) {
    | ^
  3 | //     node(id: $bookId) {
  4 | //       ... on Book {
  5 | //         title
    at e (/PROJECT_PATH/node_modules/rescript-relay/cli/cli.js:154:2200786)
    
...
```

### Mutation (and Subscription as well)

For example, let's have this piece of code:
```rescript
// module CreateBookMutation = %relay(`
//   mutation Books_createBookMutation($title: String!)
//   @raw_response_type {
//     createBook(input: {title: $title}) {
//       id
//       numberOfPages
//     }
//   }
// `)
```

For mutations (and I think subscriptions as well), it doesn't matter if code is compiled and generated beforehand, the command would report this:
```bash
...

SyntaxError: Syntax Error: Cannot parse the unexpected character "/". (2:1)
  1 |
> 2 | //   mutation Books_createBookMutation($title: String!)
    | ^
  3 | //   @raw_response_type {
  4 | //     createBook(input: {title: $title}) {
  5 | //       id
    at e (/PROJECT_PATH/node_modules/rescript-relay/cli/cli.js:154:2200786)
    
...
```

Please let me know if this is some known issue or if it is something expected.
Thanks!

**Comment by zth** [comment]
Hey!

Good catch! Would you be up for taking a stab at this? Should be fairly straight forward. Essentially, the problem is that we extract the sources to format via a regexp, but we don't account for comments. That's done here: 

https://github.com/zth/rescript-relay/blob/9a3cf37f80ec1529110321ad00543812fc377613/packages/rescript-relay-cli/cliUtils.ts#L25-L51

One solution would be to simple add a layer in `extractGraphQLSourceFromReScript`, something like:

```typescript
const extractGraphQL = makeExtractTagsFromSource(
  rescriptGraphQLTagsRegexp
);

export const extractGraphQLSourceFromReScript = (content: string) => {
  // Check for comments
  return extractGraphQL(content).filter(tag => !tag.content.split("\n").some(line => line.trim().startsWith("//"))
}
```

What do you think?

The local workflow for the CLI isn't great, but there are tests you can leverage that'll make life slightly less painful.

**Comment by zth** [comment]
Also - happy you like the CLI! 😄 I'm all ears if you have ideas for more useful things it could do.

**Comment by reck753** [comment]
Sure! I will give it a try! 
I will try to do it this weekend.

Glad to hear it! If something comes to my mind, I will let you know!
