### ISSUE TITLE
[Docs] The big docs epic

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#345]
This issue is intended to track things we (desperately) need to add to the docs. Please feel free to comment on this issue, and I'll add to the list.

## How the top level `node` field works. 
- It always checks the _cache_ (via `id`) first before going to the server. An example when this is useful is when you have a details page for a single instance of a type. Going via the cache first means Relay might be able to partially render a lot of the details view with the data that's currently in the cache, while fetching the rest of the data. 
- If you use the `node` field to fetch only one type, RescriptRelay will "collapse" the response of `node` automatically, so you don't need to select the full union (select more than 1 type to opt out)
- Because of the benefits, it might be worth it considering using `node` for details pages (I always do that to leverage all of the benefits).

**Comment by redbar0n** [comment]
Resposting [this tweet](https://x.com/magnemg/status/1709880319220802018?s=20) here:

I tried to find details of the benefits (the WHY) of [#ReScriptRelay](https://twitter.com/hashtag/ReScriptRelay?src=hashtag_click) (esp. vs. normal [#Relay](https://twitter.com/hashtag/Relay?src=hashtag_click)) but I couldn't find any... not on the landing page, docs, or github page.. the closest I've found is some tweets of yours..

[#rescript](https://twitter.com/hashtag/rescript?src=hashtag_click) comp. is obv., but like to learn more!
