### ISSUE TITLE
[docs] Document using with Next.js

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#36]
There's already a few people using ReasonRelay successfully with Next.js, like https://github.com/sync/pollen-tracker, but it should also be documented so people don't have to go through the same issues over and over.

**Comment by zth** [comment]
I think we actually should do a full template based on the excellent https://github.com/ryyppy/nextjs-default so people can get started using ReasonRelay and Next.js together really fast.

**Comment by shinzui** [comment]
What happened to the `pollen-tracker` repo?
