### ISSUE TITLE
Legacy content in document(pagination)

### ISSUE THREAD

**Issue by MinsangKim-GreenLabs** [zth/rescript-relay#363]
While I was reading the pagination document, I found [this](https://rescript-relay-documentation.vercel.app/docs/pagination#:~:text=Notice%20RescriptRelay.%7B...%7D%20%2D%20that%27s%20a%20hint%20to%20tell%20the%20compiler%20where%20to%20find%20the%20record%20we%27re%20using%2C%20which%20in%20turn%20is%20because%20the%20compiler%20cannot%20infer%20what%20record%20we%27re%20trying%20to%20destructure%20from%2C%20so%20we%20need%20to%20give%20it%20a%20hint.) line, I couldn't found any referencing `RescriptRelay` thing from the source code. I guess it's saying old API from this commit(3f2b3c).

**Comment by zth** [comment]
Fixed in the recently merged PR. Thanks!
