### ISSUE TITLE
Error occurs when passing null value to factor.

### ISSUE THREAD

**Issue by MiryangJung** [zth/rescript-relay#388]
> This issue from [Discord](https://discord.com/channels/779997538434154497/779997538434154500/1017439793778532442)

Null should be able to used though 😁

```
    somequery(
      orderDirection: DESC
      typeFilter: null
      first: 100
    )

// Error: The value null can't be found
```

**Comment by zth** [comment]
Thanks!

Closed in https://github.com/zth/rescript-relay/commit/0b34948f8494a79b135bf75a3ee737e4b3d1c95e
