### ISSUE TITLE
Clean up PPX

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#389]
* [ ] Reason -> OCaml
* [ ] Move most emitted type signatures to the central lib + use type parameters instead
* [ ] Move off of `ppxlib`

**Comment by cometkim** [comment]
Just curious, what is the main reason for converting syntax?

**Comment by zth** [comment]
One is to simplify the setup as much as possible. Another is that I'm trying to get proficient in OCaml, and using it here would help with that.
