### ISSUE TITLE
invalid types created in Connection ID makers

### ISSUE THREAD

**Issue by tsnobip** [zth/rescript-relay#390]
since #382 was merged, Connection ID makers create arguments that cannot be typed.

For example:
```graphql
calls(
      first: $callCount
      after: $cursor
      filter: {
        startTime: { lessThan: $beforeTime }
        or: [
          { phoneNumber: { includesInsensitive: $callSearchTerm } }
          { callId: { includesInsensitive: $callSearchTerm } }
        ]
      }
    )
```
gets translated to :
```rescript
let args = {"filter": {"startTime": {"lessThan": beforeTime}, "or": [{"phoneNumber": {"includesInsensitive": callSearchTerm}}, {"callId": {"includesInsensitive": callSearchTerm}}]}}
```
But `{"phoneNumber": {"includesInsensitive": callSearchTerm}}` and  `{"callId": {"includesInsensitive": callSearchTerm}}` don't have the same type so can't be in the same array.

Those arguments should be likely [be wrapped inside an unboxed variant](https://rescript-lang.org/try?code=DYUwLgBAxghswGUQwE5QBYBUQoLYQF4IAiAMwHtziAoAAQFcA7AI3IA8QATasATwAcQEFCCgRUAc0IQAgigkAKAPoBKAFzj51UJArlpAbWoRZ8hQG9i-dOUYgAcvVzMcxDZYCWjKMHqcQAM4AkowBIKEeYB4AbiBu0HCIyGhYOLgAvukqADTGpoqWsPBBnPGe3r7+waHhAZExcRpFSagY2HiZOdQAutRAA):
```rescript
@unboxed
type rec arg = Arg(_): arg
let foo = [
  Arg({"phoneNumber": {"includesInsensitive": callSearchTerm}}),
  Arg({"callId": {"includesInsensitive": callSearchTerm}}),
]
```

**Comment by zth** [comment]
Fixed in https://github.com/zth/rescript-relay/commit/b63bb5194b529c177d6da03d1401a0b56d12fc35
