### ISSUE TITLE
[V3] Things to port and fix

### ISSUE THREAD

**Issue by zth** [zth/rescript-relay#461]
- [ ] Port local enum disable safe check
- [ ] Port getConnectionNodes emit for plural fragments

**Comment by DZakh** [comment]
It also doesn't work in curried mode. This can be fixed by adding `@@uncurried` on top of the package rescript files.

**Comment by zth** [comment]
V3 is not intended to work in curried mode, it'll be full uncurried.

**Comment by DZakh** [comment]
I think `@@uncurried` won't harm until V12 or something. This way, the package stays uncurried, but people with `uncurried: false` can still use it.

**Comment by DZakh** [comment]
The only difference for them will be the need to add a dot in the callback `(. a) => ()`

**Comment by zth** [comment]
These all work for v3.
