### ISSUE TITLE
%relay ppx: This function is a curried function where an uncurried function is expected

### ISSUE THREAD

**Issue by DZakh** [zth/rescript-relay#464]
I'm migrating to ReScript 11 and got the error:
<img width="555" alt="image" src="https://github.com/zth/rescript-relay/assets/49292466/cd9926ea-c6d3-447f-a63f-f971a4f27342">

Unfortunately, I couldn't reproduce it in a sandbox, I am still trying... https://codesandbox.io/p/sandbox/rescript-sandbox-forked-6mr964
Maybe you know how it can be fixed?

- rescript@11.0.0-rc.3 (unreleased)
- rescript-relay@2.0.2
- @react/rescript@0.12.0-alpha.2
- bsconfig with uncurried: fase

**Comment by zth** [comment]
You're not trying to run in curried, right? Did you try cleaning?

**Comment by DZakh** [comment]
Yep.

**Comment by DZakh** [comment]
Can you try to compile the code in the `curried` folder https://github.com/DZakh/rescript-relay-curried-repro
It doesn't work for me.
At the same time the `uncurried` works fine, even though I didn't pass `-uncurried` to ppx.

**Comment by DZakh** [comment]
Hm, I've forked the package, checkouted to `2.x` and built ppx. Than I've added `../../../DZakh-forks/rescript-relay/packages/rescript-relay/rescript-relay-ppx/_build/default/bin/RescriptRelayPpxApp.exe` to the flags and it worked correctly. Hmmm...

**Comment by DZakh** [comment]
Can the ppx be cached on my machine somehow?

**Comment by zth** [comment]
Are you on an m1/2?

**Comment by DZakh** [comment]
m1

**Comment by zth** [comment]
Then that's probably it. I commit the built binary to the repo for m1 because there's no GitHub runner for arm. So it might be that 2.0.2 has a binary that's not updated.

**Comment by DZakh** [comment]
Could you fix it, please 😅 I'm stuck with updating our project to rescript V11

**Comment by zth** [comment]
Out in `2.0.3`, reopen if it doesn't work.

**Comment by DZakh** [comment]
I've forgotten to write back. It works now, thanks

**Comment by mishaszu** [comment]
I have the same issue with:
```
    "@rescript/core": "^1.3.0",
    "@rescript/react": "^0.12.1",
```
On Ubuntu 22.04.4 LTS (WSL)

If I run install from `rescript-relay` dir I got:
```
Error: ENOENT: no such file or directory, copyfile '/home/user/project/node_modules/rescript-relay/ppx-linux' -> '/home/user/project/node_modules/rescript-relay/ppx'
```
