### ISSUE TITLE
Blocked rescript@11 migration

### ISSUE THREAD

**Issue by DZakh** [zth/rescript-relay#467]
I've tried migrating the project at [Carla](https://www.carla.se/) to rescript@11 several times. I've fixed all the issues besides the problem with rescript-relay:

For context, we want to use `uncurried: false` since the codebase is quite big, and we want to gradually migrate to uncurried mode. Because of this, the `rescript-relay` V3 is not an option for us.

So we need to use `rescript-relay` V2 until we completely migrate to uncurried mode. But there's another problem. It uses `_` prefixes for gql fields having restricted names. In rescript@10 the `_`s were removed in runtime, but after [my PR](https://github.com/rescript-lang/rescript-compiler/pull/6354) 😅 I removed the fields mangling logic from rescript@11. This way, `rescript-relay` V2 stopped handling private keywords in rescript@11 properly, the fields in compiled js are now prefixed with `_`.

Later, I've added [the PR](https://github.com/rescript-lang/rescript-compiler/pull/6412) to allow using `@as` with `@obj` so there's a migration path from fields mangling logic.

So, now I'd like to update `rescript-relay` V2 to use `@as` instead of `_` for private keywords in the generated code. I've already taken a look in the source code and noticed a submodule written in Rust. If you tell me how to contribute to it, I'd like to give it a try. I really wish to start using rescript@11 in production.

**Comment by zth** [comment]
Sure! Check this repo out: https://github.com/zth/relay/tree/rescript-relay. It's the Relay compiler fork RescriptRelay uses. It's in the `compiler/` dir.

Place yourself in the `compiler/test-project-res` dir and run `cargo build && ../target/debug/relay`. That'll compile the compiler and run it on the test project. You'll see any changes you make reflected there.

Adding `@as()` is hopefully fairly straight forward. There should be plenty of examples in the code base.

**Comment by mununki** [comment]
Currently my project using "rescript": "v11-rc.4" and "rescript-relay": "^2.0.0" with uncurried: true. I have input type in graphQL schema:
```graphql
input ShippingFeePolicyMutationInput {
  amount: Int!
  freeShippingThreshold: Int
  quantityStep: Int
  type: ShippingFeePolicyType!
}
```
The js output has `_type` instead of `type` now with this ReScript code.
```res
Mutation.make_shippingFeePolicyMutationInput(~amount=0, ~_type=#FREE, ())
```
```js
{
  amount: 0,
  _type: "FREE"
}
```
But, I can't figure it out why because playground looks fine to me. https://rescript-lang.org/try?version=v11.0.0-beta.4&code=AIGwlgbgpgUALgTwA5QARgHZIK5wPoDKAFmEkpgOYBiUUACgPbgDGCAsrgIZxgMYCSWXKgC8qAN4xUqTgFsG2DHABc6JQBopqAGYAnWsVLkMFACpF9AZyJMAJqoZIefADyY4APk3SAjtk5KYIgEcFBIDk68GG5KXlrAnJYAFABEiCgpAJSo6VB4qgDaAMQAwgDyAHIAIvym-JUAggAyeFQASgCiHagAPqhF7V29-RVlpngNdHRN-CUNAEJN3X1FdA38VcNFAIoAqg0VdaYAmnjzDQQdVQC6mgC+MDCgkGjADABGAFaoUAAeoboMJwQKhZJwANZ5axGSg0ehMMCsDhwbhRQQ4FSoJJaaQAPzkCiUqnc3mkqFxegMJDIlHMVhsIHsajgIgA-KS8X4AjxgqFwsy2RzUAlkmlkFAsuS8LlCjiyStytVavUKs1Wp0OnLpCtBpqyfKRmMJlMZnNFnr9Vs1hstVs9gcjqdzpcqnLbnLFEEtNkRB41BjCNTjNRaIwWOwuM4BEI4KJUCkUo8QFBY7I42DIXhoTSTHCw4iIyio+jcEl8fJFCyAAzqKW5EQDDW1pKZTJAA

**Comment by mununki** [comment]
The functions and type definition are extracted from the generated modules by rescript-relay.

**Comment by DZakh** [comment]
It's the same issue I've described in the description.
That's because of the PR: https://github.com/rescript-lang/rescript-compiler/pull/6354
Fix in the PR: https://github.com/zth/relay/pull/15

**Comment by mununki** [comment]
@DZakh Can you check the playground link I've added? I'm wondering why this output has `type`.
<img width="1690" alt="image" src="https://github.com/zth/rescript-relay/assets/36963424/42f06dfe-84fa-4629-af57-2a446d761b3f">

**Comment by DZakh** [comment]
See https://github.com/rescript-lang/rescript-compiler/pull/6354.
There used to be the logic of mangling object keys up till 11-rc.3

**Comment by DZakh** [comment]
I think the change should be highlighted more in ReScript V11 release notes. It's a breaking change people should know about.

**Comment by mununki** [comment]
I opened an issue https://github.com/rescript-lang/rescript-compiler/issues/6440, if the js output is generated by the return type of the external function, then `_type` issue here would be fixed, I guess.

**Comment by DZakh** [comment]
Yes, but I think it'll be quite difficult to make it work. Also, if you noticed, in our case the type has a field called `type_`, while `external` has a field called `_type`.

**Comment by zth** [comment]
`2.1.0` is out, and should fix this. Reopen if it does not.
