### ISSUE TITLE
Timestamp type generation support

### ISSUE THREAD

**Issue by DenhamPreen** [zth/rescript-relay#471]
Current behaviour: Postgres timestamp type is being typed as `RescriptRelay.any` 

Desired behaviour: The typed mapped into some sort of date, possibly a Js.Date.t 

Screenshot of hasura dashboard of postgres table columns showing the column `created_time` type
![image](https://github.com/zth/rescript-relay/assets/26438203/887b9fb1-58e4-49ef-9e3b-f421a051b9ca)

Screenshot of the generated type 
![image](https://github.com/zth/rescript-relay/assets/26438203/1abd593b-a4e4-4e80-bffb-d64c45b88420)

cc: @mjyoung114 @jasoons

**Comment by zth** [comment]
If it's a custom scalar in the Hasura schema you can do that already easily: https://rescript-relay-documentation.vercel.app/docs/custom-scalars

**Comment by DenhamPreen** [comment]
Thanks 🙏 this is exactly what I was looking for. 

Checkout algolia search for docusaurus might make it easier for others. https://docusaurus.io/docs/search

**Comment by zth** [comment]
Would you be up for PRing that functionality to the docs? I can do the actual application to Algolia.

**Comment by DenhamPreen** [comment]
Ya sure :)

**Comment by DenhamPreen** [comment]
I'll open a new issue and assign myself
