### ISSUE TITLE
Add algolia search in docusaurus documentation

### ISSUE THREAD

**Issue by DenhamPreen** [zth/rescript-relay#472]
User story: As a dev I'd like to search the documentation related to what I'm doing, for example if I find one of my types is `RescriptRelay.any` I'd like to be able to search it in the documentation and say its would take me to [this doc](https://rescript-relay-documentation.vercel.app/docs/custom-scalars) .

[Docusaurus docs](https://docusaurus.io/docs/search)

Initial discussion [here](https://github.com/zth/rescript-relay/issues/471)

**Comment by zth** [comment]
This is now implemented and deployed to prod. Please try it out and see if we can tweak it to be better.
