### ISSUE TITLE
Fail to update from 2.1.0 to 2.2.0

### ISSUE THREAD

**Issue by DZakh** [zth/rescript-relay#476]
I get the following error when trying to use `2.2.0`:

<img width="556" alt="image" src="https://github.com/zth/rescript-relay/assets/49292466/cf1fca33-aa2d-4c2b-8fb0-d5612ffafb2f">

Also, there's a new warning:

<img width="567" alt="image" src="https://github.com/zth/rescript-relay/assets/49292466/08658058-d725-40a5-90c7-014b288feb27">

**Comment by zth** [comment]
@DZakh can you try `2.3.0`?

**Comment by DZakh** [comment]
It compiles 🤩

**Comment by DZakh** [comment]
And works 👍 Thanks for such a quick fix
