### ISSUE TITLE
BUG: Failure to resolve useBlockingPaginationFragment (and others)

### ISSUE THREAD

**Issue by brennancaldwell** [zth/rescript-relay#485]
BUG: 
Attempt to build a `rescript-relay` project using Parcel results in the following error:

```sh
@parcel/core: Failed to resolve 
'react-relay/lib/relay-hooks/useBlockingPaginationFragment' from 
'./node_modules/rescript-relay/src/RescriptRelay_Fragment.bs.js'
```

CAUSE:
As of [react-relay v16.2.0](https://github.com/facebook/relay/releases/tag/v16.2.0), a handful of hooks have been moved into a `legacy` folder in preparation for "the full rollout of the new hooks implementation" (see commit [here](https://github.com/facebook/relay/commit/a28e8c9ad7c906712560e8278be1f513750e0060)), including `FragmentResource.js`, `useBlockingPaginationFragment.js`, `useFragmentNode.js`, and `useRefetchableFragmentNode.js`. As such, `rescript-relay`'s attempt to import fails.

DEPS:
```
"react-relay": "^16.2.0",
"relay-runtime": "^16.2.0",
"rescript": "^11.0",
"rescript-relay": "3.0.0-rc.3",
```

**Comment by zth** [comment]
Thank you! Workaround for now: Stay on Relay 16.
