### ISSUE TITLE
Plugin for Jetbrains Idea

### ISSUE THREAD

**Issue by listepo** [zth/rescript-relay#486]
it would be nice to have support for Jetbrains Idea

**Comment by zth** [comment]
At least the LSP parts (autocomplete in GraphQL, etc) should be easy to test in JetBrains (I believe LSP stuff is supported, right?).

**Comment by listepo** [comment]
I think yes

**Comment by zth** [comment]
It's not something I'm going to be able to spend time on myself, but if you get it working I'm happy to link to it.
