### ISSUE TITLE
Consider hiding `.use` on `@inline` fragments

### ISSUE THREAD

**Issue by ValdemarGr** [zth/rescript-relay#506]
Relay doesn't seem to handle `InlineFrag.use(frag)` well if the fragment module `InlineFrag` has the `@inline` directive.
A strange error is thrown that makes finding the cause difficult, especially for new people.

[This seems like a bug](https://github.com/facebook/relay/issues/4450) and has been an issue for longer that the linked to issue has been open.

Here is an example of the error:
```
Uncaught Invariant Violation: GraphQLTag: Expected a fragment, got `{"kind":"InlineDataFragment","name":"ContractSharedBookingByDateFrag"}`.
    invariant browser.js:38
    getFragment GraphQLTag.js:37
    useFragment_LEGACY useFragment.js:14
    useFragment useFragment.js:31
    useFragment2 RescriptRelay_Fragment.bs.js:10
    use$9 Contract_Shared.bs.js:298
```

I'm guessing [this PPX code](https://github.com/zth/rescript-relay/blob/fd6bb880d4aa7082837b76078b01cb80ffce441a/packages/rescript-relay/rescript-relay-ppx/library/Fragment.ml#L25-L43) would have to be guarded by `!hasInlineDirective`.

**Comment by zth** [comment]
Definitely a good idea to hide. Do you want to take a stab at fixing it?

**Comment by ValdemarGr** [comment]
I opened a PR https://github.com/zth/rescript-relay/pull/507
