### ISSUE TITLE
Remove `FutureAddedValue` for client schema enums/unions

### ISSUE THREAD

**Issue by tsnobip** [zth/rescript-relay#514]
Right now, rescript-relay generates `FutureAddedValue` for enums/unions that come from client schemas. 

This doesn't really make sense given they all live in the frontend only so they can't get out of sync. We should remove this extra variant case.

**Comment by zth** [comment]
Fixed here: https://github.com/zth/relay/commit/6e0926315fe6cd062e729fc2042b523a62b00382

It's in the Relay Resolvers branch though, so it'll be a little while before it lands.

**Comment by tsnobip** [comment]
released in 3.0.0-rc.8 now I guess right?
